<?php $direct = Mage::getModel('tpg/direct'); ?>
<?php if ($direct->getConfigData('mode') == Iridiumcorp_Tpg_Model_Source_PaymentMode::PAYMENT_MODE_HOSTED_PAYMENT_FORM) {?>
	<fieldset class="form-list">
		<?php $_code=$this->getMethodCode() ?>
		<ul id="payment_form_<?php echo $_code ?>" style="display:none">
			<li>
				<img alt="<?php echo $this->__('Iridium Corporation Logo'); ?>" src="<?php echo $this->getSkinUrl('images/iridium_corporation.jpg'); ?>">
			</li>
	        <li>
	            <?php echo $this->__('You will be redirected to a secure page where you can complete your payment.') ?>
	        </li>
	    </ul>
	</fieldset>
<?php } else {?>
	<fieldset class="form-list">
		<?php $_code = $this->getMethodCode(); ?>
	    <ul id="payment_form_<?php echo $_code; ?>" style="display:none">
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_owner"><?php echo $this->__('Name On Card') ?> <span class="required">*</span></label><br/>
	                <input type="text" title="<?php echo $this->__('Name On Card') ?>" class="required-entry input-text" id="<?php echo $_code; ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>"/>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_number"><?php echo $this->__('Card Number') ?> <span class="required">*</span></label><br/>
	                <input type="text" id="<?php echo $_code; ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Card Number') ?>" class="required-entry input-text" value=""/>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_expiration"><?php echo $this->__('Expiry Date') ?> <span class="required">*</span></label><br/>
	                <div class="v-fix">
	                <select id="<?php echo $_code; ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="required-entry">
	                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
	                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
	                    <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
	                <?php endforeach ?>
	                </select>
	                </div>
	                
	                <div class="v-fix" style="padding-left:5px;">
	                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
	                <select id="<?php echo $_code; ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
	                <?php foreach ($this->getCcYears() as $k=>$v): ?>
	                    <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
	                <?php endforeach ?>
	                </select>
	                </div>
	            </div>
	        </li>
	        <li>
	        	<div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_ss_start_month"><?php echo $this->__('Start Date') ?></label><br />
	                <div class="v-fix">
	                <select id="<?php echo $_code; ?>_cc_ss_start_month" style="width:140px;" name="payment[cc_ss_start_month]" class="validate-cc-start">
	                <?php $_ccStartMonth = $this->getInfoData('cc_ss_start_month') ?>
	                <?php foreach ($this->getCcStartMonths() as $k=>$v): ?>
	                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccStartMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
	                <?php endforeach ?>
	                </select>
	                </div>
	                <div class="v-fix" style="padding-left:5px;">
	                <?php $_ccStartYear = $this->getInfoData('cc_ss_start_year') ?>
	                <select id="<?php echo $_code ?>_cc_ss_start_year" style="width:103px;" name="payment[cc_ss_start_year]">
	                <?php foreach ($this->getCcStartYears() as $k=>$v): ?>
	                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccStartYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
	                <?php endforeach ?>
	                </select>
	                </div>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_ss_issue"><?php echo $this->__('Issue Number') ?></label><br />
	                <div class="v-fix"><input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text" id="<?php echo $_code ?>_cc_ss_issue" name="payment[cc_ss_issue]" style="width:3em;" value="" /></div>
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="<?php echo $_code; ?>_cc_cid"><?php echo $this->__('CV2') ?> <span class="required">*</span></label><br/>
	                <div class="v-fix"><input type="text" title="<?php echo $this->__('CV2') ?>" class="required-entry input-text" id="<?php echo $_code; ?>_cc_cid" name="payment[cc_cid]" style="width:3em;" value=""/></div>
	                &nbsp;
	                <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
	            </div>
	        </li>
	    </ul>
	</fieldset>
<?php }?>