<?php $direct = Mage::getModel('tpg/direct'); ?>
<?php if ($direct->getConfigData('mode') != Iridiumcorp_Tpg_Model_Source_PaymentMode::PAYMENT_MODE_DIRECT_API) {?>
	<?php if ($direct->getConfigData('mode') == Iridiumcorp_Tpg_Model_Source_PaymentMode::PAYMENT_MODE_HOSTED_PAYMENT_FORM) {?>
		<?php echo $this->__('You will be redirected to a secure payment page'); ?>
	<?php } else {?>
		<?php echo $this->__('No card information is available'); ?>
	<?php }?>
<?php } else {?>
	<?php if($_info = $this->getInfo()): ?>
	<?php echo $this->__('Name on the Card: %s', $this->htmlEscape($this->getInfo()->getCcOwner())) ?>
	<br/>
	<?php echo $this->__('Card Number: xxxx-%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?>
	<br/>
	<?php echo $this->__('Expiration Date: %s/%s', $this->htmlEscape($this->getInfo()->getCcExpMonth()), $this->htmlEscape($this->getInfo()->getCcExpYear())) ?>
	<?php else: ?>
	<?php endif; ?>
<?php }?>